# Generated by Django 5.0.6 on 2024-06-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('technician_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('labtest_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('test_date', models.DateTimeField()),
                ('test_result', models.TextField()),
                ('authorized_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabTechnicians.labtechnician')),
            ],
        ),
    ]
